export type PerfilBuscaAjuda = string;

export type ItemBuscaAjuda = {
  id: string;
  titulo: string;
  descricao: string;
  rota: string;
  modulo: string | readonly string[] | null;
  perfilMinimo?: "super_admin" | "proprietario" | "gerente";
  palavrasChave: readonly string[];
  sinonimos: readonly string[];
  ordem: number;
};

export type ItemCatalogoAjuda = ItemBuscaAjuda & {
  rotasCobertas?: readonly string[];
};

function item(dados: ItemCatalogoAjuda): ItemCatalogoAjuda {
  return dados;
}

export function rotasDoItemCatalogo(entrada: ItemCatalogoAjuda) {
  const rotas = [entrada.rota, ...(entrada.rotasCobertas ?? [])];
  return [...new Set(rotas)];
}

export const CATALOGO_AJUDA: ItemCatalogoAjuda[] = [
  item({
    id: "dashboard",
    titulo: "Dashboard",
    descricao: "Resumo do dia: vendas, caixa, contas e estoque baixo.",
    rota: "/",
    modulo: "dashboard",
    palavrasChave: ["inicio", "home", "resumo"],
    sinonimos: ["pagina inicial"],
    ordem: 10,
  }),
  item({
    id: "empresa",
    titulo: "Dados da empresa",
    descricao: "Razão social, logo, telefone, Instagram e chave PIX do cupom.",
    rota: "/empresa",
    modulo: "empresa",
    palavrasChave: ["logo", "instagram", "pix", "cnpj", "endereco"],
    sinonimos: ["cadastro da empresa", "chave pix"],
    ordem: 20,
  }),
  item({
    id: "painel-tv",
    titulo: "Painel de TV",
    descricao: "Faturamento do dia e gráfico dos últimos 7 dias para a TV da loja.",
    rota: "/painel",
    modulo: "empresa",
    palavrasChave: ["tv", "painel"],
    sinonimos: ["painel tv", "painel do dia"],
    ordem: 25,
  }),
  item({
    id: "produtos",
    titulo: "Produtos",
    descricao: "Cadastro de produtos, categorias, preços e fichas técnicas.",
    rota: "/produtos",
    modulo: "produtos",
    palavrasChave: ["cardapio", "insumo", "preco"],
    sinonimos: ["cadastrar produto", "ficha tecnica"],
    ordem: 30,
  }),
  item({
    id: "produtos-novo",
    titulo: "Cadastrar produto",
    descricao: "Inclui um produto novo no cardápio ou como insumo.",
    rota: "/produtos/novo",
    modulo: "produtos",
    palavrasChave: ["novo produto", "ficha tecnica"],
    sinonimos: ["incluir produto"],
    ordem: 31,
  }),
  item({
    id: "clientes",
    titulo: "Clientes",
    descricao: "Lista e busca de clientes pessoa física e jurídica.",
    rota: "/clientes",
    modulo: "clientes",
    palavrasChave: ["cpf", "cnpj", "telefone"],
    sinonimos: ["cadastro de clientes"],
    ordem: 40,
  }),
  item({
    id: "clientes-novo",
    titulo: "Cadastrar cliente",
    descricao: "Abre o formulário de novo cliente.",
    rota: "/clientes/novo",
    modulo: "clientes",
    palavrasChave: ["novo cliente", "cpf", "cnpj"],
    sinonimos: ["incluir cliente"],
    ordem: 41,
  }),
  item({
    id: "fornecedores",
    titulo: "Fornecedores",
    descricao: "Cadastro de fornecedores usados nas compras.",
    rota: "/fornecedores",
    modulo: "fornecedores",
    palavrasChave: ["fornecedor"],
    sinonimos: ["cadastrar fornecedor"],
    ordem: 50,
  }),
  item({
    id: "fornecedores-novo",
    titulo: "Cadastrar fornecedor",
    descricao: "Inclui um fornecedor novo.",
    rota: "/fornecedores/novo",
    modulo: "fornecedores",
    palavrasChave: ["novo fornecedor"],
    sinonimos: ["incluir fornecedor"],
    ordem: 51,
  }),
  item({
    id: "usuarios",
    titulo: "Usuários",
    descricao: "Quem acessa o sistema, perfil e permissões individuais.",
    rota: "/usuarios",
    modulo: "usuarios",
    palavrasChave: ["login", "perfil", "acesso"],
    sinonimos: ["cadastrar usuario", "novo usuario"],
    ordem: 60,
  }),
  item({
    id: "usuarios-novo",
    titulo: "Cadastrar usuário",
    descricao: "Cria um usuário e define o perfil de acesso.",
    rota: "/usuarios/novo",
    modulo: "usuarios",
    palavrasChave: ["novo usuario"],
    sinonimos: ["incluir usuario"],
    ordem: 61,
  }),
  item({
    id: "funcionarios",
    titulo: "Funcionários",
    descricao: "Cadastro de funcionários e vínculo com usuário do PDV.",
    rota: "/funcionarios",
    modulo: "funcionarios",
    palavrasChave: ["colaborador", "rh"],
    sinonimos: ["cadastrar funcionario"],
    ordem: 70,
  }),
  item({
    id: "funcionarios-novo",
    titulo: "Cadastrar funcionário",
    descricao: "Inclui um funcionário novo.",
    rota: "/funcionarios/novo",
    modulo: "funcionarios",
    palavrasChave: ["novo funcionario"],
    sinonimos: ["incluir funcionario"],
    ordem: 71,
  }),
  item({
    id: "funcionarios-ferias",
    titulo: "Férias de funcionários",
    descricao: "Programa e acompanha férias pelo cadastro do funcionário.",
    rota: "/funcionarios",
    modulo: "funcionarios",
    palavrasChave: ["ferias", "rh"],
    sinonimos: ["programar ferias"],
    ordem: 72,
  }),
  item({
    id: "estoque",
    titulo: "Estoque",
    descricao: "Saldos, mínimo e movimentações.",
    rota: "/estoque",
    modulo: "estoque",
    palavrasChave: ["saldo", "insumo", "estoque baixo"],
    sinonimos: ["consultar estoque"],
    ordem: 80,
  }),
  item({
    id: "estoque-movimentacoes",
    titulo: "Movimentações de estoque",
    descricao: "Entradas, saídas e histórico de movimentação.",
    rota: "/estoque?aba=movimentacoes",
    modulo: "estoque",
    palavrasChave: ["entrada", "saida", "historico"],
    sinonimos: ["historico de estoque"],
    ordem: 81,
  }),
  item({
    id: "estoque-ajuste",
    titulo: "Ajuste de estoque",
    descricao: "Ajuste manual de saldo, positivo ou negativo.",
    rota: "/estoque?aba=ajuste",
    modulo: "estoque",
    palavrasChave: ["ajuste", "corrigir saldo"],
    sinonimos: ["ajuste manual"],
    ordem: 82,
  }),
  item({
    id: "producao",
    titulo: "Produção",
    descricao: "Baixa insumos da ficha técnica e entra o produto final no estoque.",
    rota: "/producao",
    modulo: "producao",
    palavrasChave: ["fabricar", "ficha tecnica", "lote"],
    sinonimos: ["producao", "produzir"],
    ordem: 90,
  }),
  item({
    id: "producao-nova",
    titulo: "Nova produção",
    descricao: "Registra um lote de produção com baixa atômica dos insumos.",
    rota: "/producao/nova",
    modulo: "producao",
    palavrasChave: ["produzir", "lote"],
    sinonimos: ["lancar producao"],
    ordem: 91,
  }),
  item({
    id: "producao-cancelar",
    titulo: "Cancelar produção",
    descricao: "Estorna um lote confirmado e devolve os insumos ao estoque.",
    rota: "/producao",
    modulo: "cancelar_producao",
    palavrasChave: ["cancelar producao", "estorno"],
    sinonimos: ["desfazer producao"],
    ordem: 92,
  }),
  item({
    id: "etiquetas",
    titulo: "Etiquetas",
    descricao: "Imprime etiquetas de produto com código de barras e ingredientes.",
    rota: "/etiquetas",
    modulo: "etiquetas",
    palavrasChave: ["etiqueta", "codigo de barras", "impressao"],
    sinonimos: ["imprimir etiqueta"],
    ordem: 100,
  }),
  item({
    id: "compras",
    titulo: "Compras",
    descricao: "Entrada de mercadoria, estoque e contas a pagar.",
    rota: "/compras",
    modulo: "compras",
    palavrasChave: ["compra", "entrada", "xml"],
    sinonimos: ["nota de entrada"],
    ordem: 110,
  }),
  item({
    id: "compras-nova",
    titulo: "Lançar entrada de mercadoria",
    descricao: "Registra NF-e de entrada para estoque e contas a pagar.",
    rota: "/compras/nova",
    modulo: "compras",
    palavrasChave: ["xml", "fornecedor", "mercadoria", "entrada"],
    sinonimos: ["nota fiscal de entrada", "nf-e entrada"],
    ordem: 111,
  }),
  item({
    id: "pdv",
    titulo: "Abrir o PDV",
    descricao:
      "Ponto de venda: itens, cliente (F8), frete, PIX no cupom, desconto e pagamento.",
    rota: "/pdv",
    modulo: "pdv",
    palavrasChave: ["venda", "terminal", "cupom", "frete", "desconto", "f8"],
    sinonimos: [
      "ponto de venda",
      "localizar cliente",
      "observacao cupom",
      "finalizar venda",
    ],
    ordem: 120,
  }),
  item({
    id: "pedidos",
    titulo: "Pedidos",
    descricao: "Pré-venda: montar, enviar, aprovar e converter em venda.",
    rota: "/pedidos",
    modulo: "pedidos",
    palavrasChave: ["pedido", "pre-venda", "orcamento"],
    sinonimos: ["lista de pedidos"],
    ordem: 130,
  }),
  item({
    id: "pedidos-novo",
    titulo: "Novo pedido",
    descricao: "Cria um pedido de cliente para depois converter no PDV.",
    rota: "/pedidos/novo",
    modulo: "pedidos",
    palavrasChave: ["montar pedido"],
    sinonimos: ["cadastrar pedido"],
    ordem: 131,
  }),
  item({
    id: "caixa",
    titulo: "Abrir ou fechar o caixa",
    descricao: "Abertura com fundo de troco e fechamento do caixa do dia.",
    rota: "/caixa",
    modulo: "caixa",
    palavrasChave: ["abertura", "fechamento", "troco", "fundo"],
    sinonimos: ["abrir caixa", "fechar caixa"],
    ordem: 140,
  }),
  item({
    id: "vendas-hoje",
    titulo: "Vendas do dia",
    descricao: "Vendas finalizadas hoje, valores, cupom e detalhe.",
    rota: "/vendas/hoje",
    modulo: "vendas",
    palavrasChave: ["cupom", "venda"],
    sinonimos: ["ver vendas", "vendas de hoje"],
    ordem: 150,
  }),
  item({
    id: "vendas-cancelar",
    titulo: "Cancelar venda finalizada",
    descricao:
      "Estorna pagamentos e devolve estoque de uma venda já finalizada.",
    rota: "/vendas/hoje",
    modulo: "cancelar_venda",
    palavrasChave: ["cancelar venda", "estorno", "devolucao"],
    sinonimos: ["desfazer venda"],
    ordem: 151,
  }),
  item({
    id: "notas-fiscais",
    titulo: "Notas fiscais NFC-e e NF-e",
    descricao: "NFC-e e NF-e emitidas a partir das vendas.",
    rota: "/notas-fiscais",
    modulo: "vendas",
    palavrasChave: ["nfce", "nfe", "cupom fiscal", "nota"],
    sinonimos: ["nota fiscal", "nfc-e", "nf-e", "nfe saida"],
    ordem: 160,
  }),
  item({
    id: "financeiro",
    titulo: "Financeiro",
    descricao: "DRE, faturamento, despesas, contas a receber e taxas de cartão.",
    rota: "/financeiro",
    modulo: "financeiro",
    palavrasChave: ["dre", "despesa", "receber"],
    sinonimos: ["contas"],
    ordem: 170,
  }),
  item({
    id: "financeiro-resumo",
    titulo: "Resumo financeiro (DRE)",
    descricao: "DRE do mês, receitas e despesas.",
    rota: "/financeiro?aba=resumo",
    modulo: "financeiro",
    palavrasChave: ["dre", "resumo"],
    sinonimos: ["demonstrativo"],
    ordem: 171,
  }),
  item({
    id: "financeiro-faturamento",
    titulo: "Faturamento",
    descricao: "Faturamento bruto e líquido do período.",
    rota: "/financeiro?aba=faturamento",
    modulo: "financeiro",
    palavrasChave: ["bruto", "liquido"],
    sinonimos: ["receita"],
    ordem: 172,
  }),
  item({
    id: "financeiro-despesas",
    titulo: "Contas a pagar",
    descricao: "Despesas e contas a pagar.",
    rota: "/financeiro?aba=despesas",
    modulo: "financeiro",
    palavrasChave: ["pagar", "despesa", "boleto"],
    sinonimos: ["conta a pagar"],
    ordem: 173,
  }),
  item({
    id: "financeiro-pagar-nova",
    titulo: "Nova conta a pagar",
    descricao: "Lança uma despesa ou conta a pagar.",
    rota: "/financeiro/pagar/nova",
    modulo: "financeiro",
    palavrasChave: ["lancar despesa"],
    sinonimos: ["nova despesa"],
    ordem: 174,
  }),
  item({
    id: "financeiro-receber",
    titulo: "Contas a receber",
    descricao: "Valores a receber de vendas.",
    rota: "/financeiro?aba=receber",
    modulo: "financeiro",
    palavrasChave: ["receber"],
    sinonimos: ["conta a receber"],
    ordem: 175,
  }),
  item({
    id: "financeiro-receber-nova",
    titulo: "Nova conta a receber",
    descricao: "Lança um valor a receber.",
    rota: "/financeiro/receber/nova",
    modulo: "financeiro",
    palavrasChave: ["lancar receber"],
    sinonimos: ["novo recebimento"],
    ordem: 176,
  }),
  item({
    id: "financeiro-taxas",
    titulo: "Taxas de cartão",
    descricao: "Percentuais cobrados pela maquininha por forma e parcelas.",
    rota: "/financeiro?aba=taxas",
    modulo: "financeiro",
    palavrasChave: ["taxa", "cartao", "maquininha", "parcela"],
    sinonimos: ["taxa de cartao", "taxa cartao"],
    ordem: 177,
  }),
  item({
    id: "relatorios",
    titulo: "Relatórios",
    descricao: "Atalhos para faturamento, estoque, margem, comissões e inventário.",
    rota: "/relatorios",
    modulo: "relatorios",
    palavrasChave: ["relatorio"],
    sinonimos: ["relatorios"],
    ordem: 180,
  }),
  item({
    id: "inventario",
    titulo: "Inventário físico",
    descricao: "Contagem física e conferência de saldo.",
    rota: "/relatorios/inventario",
    modulo: "relatorios",
    palavrasChave: ["contagem", "inventario"],
    sinonimos: ["inventario fisico"],
    ordem: 181,
  }),
  item({
    id: "inventario-novo",
    titulo: "Novo inventário",
    descricao: "Inicia uma contagem física de estoque.",
    rota: "/relatorios/inventario/novo",
    modulo: "relatorios",
    palavrasChave: ["nova contagem"],
    sinonimos: ["abrir inventario"],
    ordem: 182,
  }),
  item({
    id: "produtos-mais-vendidos",
    titulo: "Produtos mais vendidos",
    descricao: "Ranking por quantidade e valor no período.",
    rota: "/relatorios/produtos-mais-vendidos",
    modulo: "relatorios",
    palavrasChave: ["ranking", "mais vendidos"],
    sinonimos: [],
    ordem: 183,
  }),
  item({
    id: "margem",
    titulo: "Margem por produto",
    descricao: "Receita, custo e margem de cada item.",
    rota: "/relatorios/margem",
    modulo: "relatorios",
    palavrasChave: ["margem", "custo", "lucro"],
    sinonimos: ["margem de lucro"],
    ordem: 184,
  }),
  item({
    id: "comissoes",
    titulo: "Comissões",
    descricao: "Comissão de vendedor por período.",
    rota: "/relatorios/comissoes",
    modulo: "relatorios",
    palavrasChave: ["comissao", "vendedor"],
    sinonimos: ["comissao de venda"],
    ordem: 185,
  }),
  item({
    id: "saude",
    titulo: "Saúde do sistema",
    descricao: "Verificações diárias de integridade do banco e do fluxo.",
    rota: "/saude",
    modulo: "saude",
    palavrasChave: ["verificacao", "integridade"],
    sinonimos: ["saude"],
    ordem: 190,
  }),
  item({
    id: "saude-backup",
    titulo: "Backup do banco",
    descricao: "Cópias semanais do banco. Só super admin.",
    rota: "/saude?aba=backups",
    modulo: "saude",
    palavrasChave: ["backup", "copia"],
    sinonimos: ["restaurar backup"],
    ordem: 191,
  }),
  item({
    id: "auditoria",
    titulo: "Auditoria",
    descricao: "Log de ações sensíveis: quem alterou o quê.",
    rota: "/auditoria",
    modulo: "auditoria",
    palavrasChave: ["log", "rastreio"],
    sinonimos: ["historico de acoes"],
    ordem: 200,
  }),
  item({
    id: "permissoes",
    titulo: "Permissões",
    descricao: "Libera ou bloqueia módulos por perfil.",
    rota: "/permissoes",
    modulo: null,
    perfilMinimo: "proprietario",
    palavrasChave: ["acesso", "perfil", "modulo"],
    sinonimos: ["permissoes"],
    ordem: 210,
  }),
  item({
    id: "ajuda",
    titulo: "Perguntas de ajuda",
    descricao: "Itens extras da busca Ctrl+K. O catálogo do sistema é fixo.",
    rota: "/ajuda/gerenciar",
    modulo: null,
    perfilMinimo: "gerente",
    palavrasChave: ["faq", "ajuda", "ctrl+k"],
    sinonimos: ["buscar ajuda"],
    ordem: 220,
  }),
  item({
    id: "ajuda-nova",
    titulo: "Nova pergunta de ajuda",
    descricao: "Cadastra um texto extra na busca, além do catálogo.",
    rota: "/ajuda/gerenciar/novo",
    modulo: null,
    perfilMinimo: "gerente",
    palavrasChave: ["faq", "nova pergunta"],
    sinonimos: [],
    ordem: 221,
  }),
  item({
    id: "minha-conta",
    titulo: "Minha conta",
    descricao: "Troque sua senha a qualquer momento.",
    rota: "/minha-conta",
    rotasCobertas: ["/trocar-senha"],
    modulo: null,
    palavrasChave: ["senha", "perfil", "email"],
    sinonimos: ["trocar senha", "alterar senha"],
    ordem: 230,
  }),
];
